### ISSUE TITLE
Warn users when using type unstable problem parameters

### ISSUE THREAD

**Issue by csimal** [SciML/SciMLBase.jl#449]
Wrapping problem parameters in an array is an easy mistake to make that can hurt performance when parameters don't all have the same type.

It would be nice to display a message when the parameters of a problem are type unstable, and suggest to wrap parameters in something like a tuple instead, both for new users learning Julia/DiffEq and for old ones that still occasionally make this kind of mistake (me included). This kind of gotcha is easy to miss, so telling the user about it in context seems like an effective way to teach best practices.

![image](https://github.com/SciML/SciMLBase.jl/assets/45844176/e1249e09-8e9b-41c0-8ac0-afe9b4c1fc7f)

I have a working proof of concept [here](https://github.com/SciML/SciMLBase.jl/compare/master...csimal:SciMLBase.jl:master) and I'm ready to turn it into a PR, modulo possible adjustments to fit to the style guide.

**Comment by ChrisRackauckas** [comment]
RFC: @YingboMa @chriselrod @Vaibhavdixit02  . I see the good and bad of this. It would be good to make sure there is a way to turn this off. Maybe `performance_warn = false`, but it's true by default, and then it's a general thing that we should warn about potential performance issues. I think it might be a nice thing to be louder about but I'd like to hear the comments from others. I think if we do this for differential equations then we should do it for all problem types.

**Comment by csimal** [comment]
> I think if we do this for differential equations then we should do it for all problem types.
Of course! I just implemented a minimal example, but it's just one line to add to problem constructors.

**Comment by chriselrod** [comment]
If it were up to me, type instabilities wouldn't even compile. ;)

**Comment by ChrisRackauckas** [comment]
Thinking about this a bunch, I really like this. SciML is very focused on high performance. People are mad when they don't get that performance, and most of the time it's their fault. For most things people do in Julia, performance doesn't matter. You don't want Julia to be loud about every type instability in Plots.jl or HTTP.jl because you want to rely on that dynamism. But you do want to be loud about it in the simulators because those are made to be fast. A lot of the "bad benchmarks" come down to "well I didn't know any better". Well here you go, you were told by a warning to not do this if you want a good and fast simulation, and you ignored it. It's your fault. Assigning fault with software is something that I have learned over time is a very helpful meta idea. When users are told they did something wrong, they listen. When they aren't told, they think they used the software correctly. We would say obvious dynamic dispatches in a simulation is bad code smell, so we should tell people.

Now we should probably have an equally good system for turning it off. This means we should probably use Preferences.jl and have a `PERFORMANCE` preference that defaults to true. Then we would have a keyword argument `warn_performance = Preferences. ...` for handling that.

So then what else should we warn about? Here's a few things that come to mind:

- If someone has a Dictionary with return types of `Any`.
- Train ride ending...

Element type of Any should just have an early error if it's in the u0 definition because I don't think any of the solvers will actually work with it.

**Comment by csimal** [comment]
One thought is that parameters probably need to be checked recursively.
For example NetworkDynamics encourages to store parameters as `(vertex_params, edge_params)` (see https://pik-icone.github.io/NetworkDynamics.jl/dev/parameters/)

So things would look something like 
```julia
should_warn_paramtype(p::AbstractArray) = isabstracttype(eltype(p))
should_warn_paramtype(p::Dict{K,V}) where {K,V} = isabstracttype(V)
should_warn_paramtype(p::Tuple) = any(should_warn_param_type, p) 
should_warn_paramtype(p::NamedTuple) = any(should_warn_param_type, p) 
should_warn_paramtype(p) = false
```
Not sure if this should also handle structs.

I'm looking into Preferences.jl. In the meantime I have some questions.

- When should the warning be emitted? When constructing the problem, or also when passing to solve?
- Should it be `@warn` or `@info`? I used `@info` under the assumption that "Hey, this is suboptimal and you might want to know, but if you do want to shoot yourself in the foot we won't stop you".
 > Train ride ending...
- unsure what you mean

**Comment by csimal** [comment]
This is what I have so far.
```julia
const PERFORMANCE_WARNINGS = Preferences.@load_preference("PERFORMANCE_WARNINGS", true)

function set_performance_warnings!(b::Bool)
    Preferences.@set_preferences!("PERFORMANCE_WARNINGS" => b)
    if b
        @info("Performance Warnings enabled. Restart Julia for this change to take effect.")
    else
        @info("Performance Warnings disabled. Restart Julia for this change to take effect.")
    end
end

should_warn_paramtype(p::AbstractArray) = isabstracttype(eltype(p))
should_warn_paramtype(::Dict{K,V}) where {K,V} = isabstracttype(V)
should_warn_paramtype(p::AbstractArray{<:AbstractArray}) = any(should_warn_paramtype, p)
should_warn_paramtype(p::Tuple) = any(should_warn_paramtype, p) 
should_warn_paramtype(p::NamedTuple) = any(should_warn_paramtype, p)
should_warn_paramtype(p) = false 

const WARN_PARAMTYPE_MESSAGE = "Using arrays to store parameters of different types can hurt performance. Consider using tuples instead."

"""
    warn_paramtype(p, warn_performance=PERFORMANCE_WARNINGS)
Inspect the type of `p` and emit a warning if it could hurt performance when used to hold problem parameters.
The warning can be turned off by setting `warn_performance` to `false`. To turn it off globally, call `set_performance_warnings!(false)`. This will take effect after restarting Julia.
"""
function warn_paramtype(p, warn_performance = PERFORMANCE_WARNINGS)
    if warn_performance && should_warn_paramtype(p)
        @info(WARN_PARAMTYPE_MESSAGE)
    end
end
```
Unsure about the dispatch on nested arrays.

**Comment by csimal** [comment]
@ChrisRackauckas Thoughts on the above?

**Comment by ChrisRackauckas** [comment]
Yes that looks right.

**Comment by csimal** [comment]
Cool. I'll prepare a PR shortly.
